Repository MinhPhu0304/Seer, pull requests merged in 2020-05, with the labels that each got.

#5 Created the ArticleList page and installed Materials UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ArticleList.css
  frontend/src/ArticleList.js
Labels: enhancement

#10 Add Heroku build script
  README.md
  package.json
Labels: CI/CD

#13 Enhance/search
  dbConnection.js
  frontend/src/App.jsx
  frontend/src/components/progress.jsx
  frontend/src/components/search/constants.js
  frontend/src/components/search/helper.js
  frontend/src/components/search/index.jsx
  frontend/src/components/search/search.css
  frontend/src/index.js
  frontend/src/theme.jsx
  routers/index.js
  routers/search.js
  server.js
Labels: enhancement

#14 Feat/travis ci
  .eslintrc.json
  .travis.yml
  frontend/.eslintrc.json
  frontend/package.json
  package.json
  routers/search.js
Labels: CI/CD

#18 Feat add unit test
  .travis.yml
  frontend/src/App.test.js
  frontend/src/components/search/helper.test.js
Labels: enhancement

#20 Feat/react navigation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/pages/home/index.jsx
  frontend/src/components/pages/home/seer.svg
  frontend/src/components/pages/manage/index.jsx
  server.js
Labels: enhancement

#21 Add user model for MongoDB
  model/article.js
  model/user.js
Labels: Database, enhancement
